---
- name: Template
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Template
      ansible.builtin.template:
        src: "{{ template_src }}"
        dest: "{{ template_dest }}"
        mode: '0600'

    - name: Slurp
      ansible.builtin.slurp:
        path: "{{ template_dest }}"
